version: '3.8'

services:
  php-apache:
    image: php:8.2-apache
    container_name: eventx_php
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./config:/var/www/config
    ports:
      - "8080:80"
    networks:
      - eventx-net
    depends_on:
      - db
    build:
      context: ./docker/php
    restart: always

  db:
    image: mysql:8.0
    container_name: eventx_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventx
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - eventx-net

volumes:
  db_data:

networks:
  eventx-net:
    driver: bridge
