version: '3.8'

services:
  api:
    image: php:8.2-apache
    container_name: eventx_api
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    networks:
      - eventx-net
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
    restart: always

  front-end:
    image: php:8.2-apache
    container_name: eventx_front-end
    environment:
      API_URL: http://api/api
    volumes:
      - ./front-end:/var/www/html
    ports:
      - "8080:80"
    networks:
      - eventx-net
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always

  db:
    image: mysql:8.0
    container_name: eventx_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./api/sql:/docker-entrypoint-initdb.d:ro
    networks:
      - eventx-net

volumes:
  db_data:

networks:
  eventx-net:
    driver: bridge
